### ISSUE TITLE
the driver doesn't populate IPAddress variable in the base driver config

### ISSUE THREAD

**Issue by galal-hussein** [cloud-ca/docker-machine-driver-cloudca#10]
I noticed that the driver doesn't populate the IPAddress field https://github.com/docker/machine/blob/15fd4c70403bab784d91031af02d9e169ce66412/libmachine/drivers/base.go#L17 in the base driver config, instead it populates its own variable https://github.com/cloud-ca/docker-machine-driver-cloudca/blob/master/cloudca.go#L85 `PublicIp`

**Comment by pdube** [comment]
Hi Galal,

Thanks for looking into this. The IPAddress field isn't set because we updated the GetIP function to return either a PublicIP address or a private IP address depending on the docker setup. Is the field used instead of calling GetIP() in Rancher v2? This was working with Rancher v1.6

**Comment by pdube** [comment]
Is Rancher v2 loading the Drivers the same way as v1? Looks like [this](https://github.com/rancher/rancher/blob/8e7761d2a65bc8afb677153399f816186ba8b7d7/pkg/nodeconfig/config.go#L105) might be part of the issue?

**Comment by pdube** [comment]
I updated to use the IPAdress and it works. I am relatively sure that the scenario where a PublicIP should be used will not work, but we can deal with that later. Thanks for the help!

**Comment by pdube** [comment]
Fixed in #12
